#!/usr/bin/env python3
"""Generate the measurement firmware's assembly from experiments/pie-timing/cases.json.

Every measured sequence is emitted as a real function so the compiler cannot reorder or optimise the
instruction under test away: the point of the experiment is the behaviour of a *specific* instruction
sequence on silicon, and C cannot express "issue these two instructions one cycle apart".

For each case and issue distance `d` two functions are emitted:

  m_<id>_d<d>_dep    : <producer> ; (d-1) x filler ; <consumer_dep>
  m_<id>_d<d>_indep  : <producer> ; (d-1) x filler ; <consumer_indep>

Both run <iterations> times and return the CCOUNT delta. The independent variant has the same instruction
count and the same producer, only the consumer reads different registers, so the difference per iteration is
the interlock caused by the dependency. Loop overhead cancels between the two.

    .venv/bin/python tools/gen_pie_timing_asm.py                 # write measure.S / measure.h
    .venv/bin/python tools/gen_pie_timing_asm.py --check         # fail if regeneration differs (CI)
"""
from __future__ import annotations

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CASES = os.path.join(ROOT, "experiments", "pie-timing", "cases.json")
OUT_ASM = os.path.join(ROOT, "experiments", "pie-timing", "firmware", "main", "measure.S")
OUT_HDR = os.path.join(ROOT, "experiments", "pie-timing", "firmware", "main", "measure.h")

HEADER = """/* Generated by tools/gen_pie_timing_asm.py -- do not edit by hand.
 *
 * Each function measures one instruction sequence <iterations> times and returns the CCOUNT delta.
 *   dep   : the consumer reads the register the producer wrote
 *   indep : identical instruction count, consumer reads unrelated registers
 * The per-iteration interlock is (dep - indep) / iterations.
 */
"""


def func(name: str, body: list[str], iterations: int) -> str:
    # ABI: these are called through a function pointer with call8, which rotates the register window.
    # Only ENTRY/RETW pairs restore it -- a bare `ret` leaves the window rotated and the *caller* then
    # runs on the callee's registers (observed on hardware: the next call received a2=3 and the PIE
    # load faulted at address 0). The frame is unused, but the entry/retw pair is not optional.
    #
    # IRAM: the loop body runs from .iram1, not from flash. Executing from flash (XIP) makes every
    # instruction fetch a cache lookup whose latency depends on what else walked through the cache, and
    # that variance lands directly in the CCOUNT delta -- it is what kept the noise floor above the
    # 0.5-cycle bound the parser accepts. IRAM fetches are deterministic.
    #
    # The address registers are re-seeded at the top of every iteration. The PIE memory forms
    # (EE.LD.ACCX.IP, EE.ST.ACCX.IP, EE.LD.128.USAR.IP) *post-increment* their `as` operand, so without
    # this the loop walks 16 bytes per iteration -- 32 KB past a 256-byte buffer -- and would fault (or
    # silently touch memory it does not own). Re-seeding also keeps the accessed set to 32 bytes, so the
    # whole loop stays in one cache line instead of streaming through the D-cache. Both variants of a
    # case get the identical seeding, so it cancels out of the (dep - indep) difference.
    lines = [
        '    .section .iram1,"ax",@progbits',
        "    .align 4",
        f"    .global {name}",
        f"    .type {name},@function",
        f"{name}:",
        "    entry a1, 32",
        f"    movi a6, {iterations}",
        "    rsr.ccount a7",
        f".Lloop_{name}:",
        "    mov a3, a2",                       # a3 = caller's buffer (the TRM's `as`)
        "    addi a4, a2, 16",                  # a4 = the second address the independent variants use
    ]
    lines += [f"    {ins}" for ins in body]
    lines += [
        "    addi a6, a6, -1",
        f"    bnez a6, .Lloop_{name}",
        "    rsr.ccount a2",
        "    sub a2, a2, a7",
        "    retw.n",
        f"    .size {name}, .-{name}",
        "",
    ]
    text = "\n".join(lines)
    # Invariant: every generated function must return through a window-restoring retw. A plain `ret`
    # silently corrupts the caller -- it compiles, flashes, runs, and produces garbage.
    if "retw.n" not in text or any(l.strip() == "ret" for l in lines):
        raise SystemExit(f"generator bug: {name} does not return with retw")
    return text


def build(cases: dict) -> tuple[str, str]:
    iterations = int(cases["iterations"])
    filler = list(cases.get("filler", ["add a14, a13, a12"]))
    asm = [HEADER]
    decls: list[tuple[str, int]] = []

    for case in cases["cases"]:
        cid = case["id"]
        for d in case["distances"]:
            for variant, consumer in (("dep", case["consumer_dep"]), ("indep", case["consumer_indep"])):
                name = f"m_{cid}_d{d}_{variant}"
                body = list(case["producer"]) + filler * (d - 1) + list(consumer)
                asm.append(func(name, body, iterations))
                decls.append((name, d))

    for item in cases.get("alone", []):
        name = f"m_{item['id']}_alone"
        asm.append(func(name, list(item["body"]), iterations))
        decls.append((name, 1))

    hdr = [HEADER, "#ifndef MEASURE_H", "#define MEASURE_H", "#include <stdint.h>", ""]
    for name, _d in decls:
        hdr.append(f"uint32_t {name}(void *buf);")
    hdr += ["", "#endif", ""]
    return "\n".join(asm), "\n".join(hdr)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify the committed files match the generator")
    ap.add_argument("--cases", default=CASES)
    a = ap.parse_args()
    cases = json.load(open(a.cases, encoding="utf-8"))
    asm, hdr = build(cases)

    if a.check:
        bad = []
        for path, want in ((OUT_ASM, asm), (OUT_HDR, hdr)):
            have = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
            if have != want:
                bad.append(path)
        if bad:
            print("FAIL: generated files differ from cases.json: " + ", ".join(bad))
            return 1
        print(f"ok: {os.path.relpath(OUT_ASM, ROOT)} and {os.path.relpath(OUT_HDR, ROOT)} are up to date")
        return 0

    os.makedirs(os.path.dirname(OUT_ASM), exist_ok=True)
    open(OUT_ASM, "w", encoding="utf-8").write(asm)
    open(OUT_HDR, "w", encoding="utf-8").write(hdr)
    n_cases = len(cases["cases"]) + len(cases.get("alone", []))
    print(f"wrote {os.path.relpath(OUT_ASM, ROOT)} ({n_cases} sequences) and measure.h")
    return 0


if __name__ == "__main__":
    sys.exit(main())
