#!/usr/bin/env python3
"""Generate the measurement firmware's assembly from experiments/pie-timing/cases.json.

Every measured sequence is emitted as a real function so the compiler cannot reorder or optimise the
instruction under test away: the point of the experiment is the behaviour of a *specific* instruction
sequence on silicon, and C cannot express "issue these two instructions one cycle apart".

For each case and issue distance `d` two functions are emitted:

  m_<id>_d<d>_dep    : <producer> ; (d-1) x filler ; <consumer_dep>
  m_<id>_d<d>_indep  : <producer> ; (d-1) x filler ; <consumer_indep>

Both run <iterations> times and return the CCOUNT delta. The independent variant has the same instruction
count and the same producer, only the consumer reads different registers, so the difference per iteration is
the interlock caused by the dependency. Loop overhead cancels between the two.

    .venv/bin/python tools/gen_pie_timing_asm.py                 # write measure.S / measure.h
    .venv/bin/python tools/gen_pie_timing_asm.py --check         # fail if regeneration differs (CI)
"""
from __future__ import annotations

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CASES = os.path.join(ROOT, "experiments", "pie-timing", "cases.json")
OUT_ASM = os.path.join(ROOT, "experiments", "pie-timing", "firmware", "main", "measure.S")
OUT_HDR = os.path.join(ROOT, "experiments", "pie-timing", "firmware", "main", "measure.h")

HEADER = """/* Generated by tools/gen_pie_timing_asm.py -- do not edit by hand.
 *
 * Each function measures one instruction sequence <iterations> times and returns the CCOUNT delta.
 *   dep   : the consumer reads the register the producer wrote
 *   indep : identical instruction count, consumer reads unrelated registers
 * The per-iteration interlock is (dep - indep) / iterations.
 */
"""


def func(name: str, body: list[str], iterations: int) -> str:
    lines = [
        "    .text",
        "    .align 4",
        f"    .global {name}",
        f"    .type {name},@function",
        f"{name}:",
        "    mov a3, a2",                       # a2 = caller's buffer; a3 = the PIE address operand (as)
        f"    movi a6, {iterations}",
        "    rsr.ccount a7",
        f".Lloop_{name}:",
    ]
    lines += [f"    {ins}" for ins in body]
    lines += [
        "    addi a6, a6, -1",
        f"    bnez a6, .Lloop_{name}",
        "    rsr.ccount a2",
        "    sub a2, a2, a7",
        "    ret",
        f"    .size {name}, .-{name}",
        "",
    ]
    return "\n".join(lines)


def build(cases: dict) -> tuple[str, str]:
    iterations = int(cases["iterations"])
    filler = list(cases.get("filler", ["add a14, a13, a12"]))
    asm = [HEADER]
    decls: list[tuple[str, int]] = []

    for case in cases["cases"]:
        cid = case["id"]
        for d in case["distances"]:
            for variant, consumer in (("dep", case["consumer_dep"]), ("indep", case["consumer_indep"])):
                name = f"m_{cid}_d{d}_{variant}"
                body = list(case["producer"]) + filler * (d - 1) + list(consumer)
                asm.append(func(name, body, iterations))
                decls.append((name, d))

    for item in cases.get("alone", []):
        name = f"m_{item['id']}_alone"
        asm.append(func(name, list(item["body"]), iterations))
        decls.append((name, 1))

    hdr = [HEADER, "#ifndef MEASURE_H", "#define MEASURE_H", "#include <stdint.h>", ""]
    for name, _d in decls:
        hdr.append(f"uint32_t {name}(void *buf);")
    hdr += ["", "#endif", ""]
    return "\n".join(asm), "\n".join(hdr)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify the committed files match the generator")
    ap.add_argument("--cases", default=CASES)
    a = ap.parse_args()
    cases = json.load(open(a.cases, encoding="utf-8"))
    asm, hdr = build(cases)

    if a.check:
        bad = []
        for path, want in ((OUT_ASM, asm), (OUT_HDR, hdr)):
            have = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
            if have != want:
                bad.append(path)
        if bad:
            print("FAIL: generated files differ from cases.json: " + ", ".join(bad))
            return 1
        print(f"ok: {os.path.relpath(OUT_ASM, ROOT)} and {os.path.relpath(OUT_HDR, ROOT)} are up to date")
        return 0

    os.makedirs(os.path.dirname(OUT_ASM), exist_ok=True)
    open(OUT_ASM, "w", encoding="utf-8").write(asm)
    open(OUT_HDR, "w", encoding="utf-8").write(hdr)
    n_cases = len(cases["cases"]) + len(cases.get("alone", []))
    print(f"wrote {os.path.relpath(OUT_ASM, ROOT)} ({n_cases} sequences) and measure.h")
    return 0


if __name__ == "__main__":
    sys.exit(main())
